# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bcd3e9e77c88d025a146e0dfb69525c26c24d1c3e52b0b027873b3cfcbac758979e6611555e92f06c94835ce868d3c6e03b77346941f05149e35dc46dd292a

test:
  secret_key_base: f515c941c3836584ae4cdd166c774dfdd96a86b5617d0519be67904d9898aa5e2d450a9c0a5c8d5efa969d8d519ae9d6347037b1562c33827a6c3e3f1b45a550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
